<?php   
//function fillfdf($rows){
//for($i=0;$i<7;$i++){
//echo ($rows[$i][3]." , ");
//}
$fdffile1 = fopen("tmp/new-ill-fdf", "w") or die("unable to open file for writing");
if($fdffile1){

//common to all FDFs
fwrite($fdffile1, "%FDF-1.2\r\n") ;
fwrite($fdffile1, "%âãÏÓ\r\n") ;
//fwrite($fdffile1, "%FDF-1.2\r\n") ;
fwrite($fdffile1, "1 0 obj\r\n"); 
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/FDF\r\n"); 
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/Fields [\r\n");
// Field List
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (" );
fwrite($fdffile1, $rows[6][4]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row7LEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[0][5]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row1SubscriberCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[0][3]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row1PercentPortfolio)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[0][5]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row2SubscriberCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[5][6]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row6SubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[1][3]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row2PercentPortfolio)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $subscriber_full_name);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (SubscribersName)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[4][4]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row5LEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[2][5]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row3SubscriberCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[3][4]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row4LEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $total_cost);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (TotalCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $total_maturity_distribution);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (TotalProjectedYTM)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[3][5]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row4SubscriberCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[6][5]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row7SubscriberCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[5][4]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row6LEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, "");
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (JointBuyerInitial)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[4][5]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row5SubscriberCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $totalfaceamount);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (TotalFaceAmount)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[3][3]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row4PercentPortfolio)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[0][6]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row1SubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, "");
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (PrimaryBuyerInitialDate)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[5][5]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row6SubscriberCostBasis)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, "");
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (PrimaryBuyerInitial)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[0][4]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row1LEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[1][6]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row2SubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $avg_LE);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (AverageLE)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[2][6]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row3SubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $total_maturity_distribution);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (TotalSubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[2][3]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row3PercentPortfolio)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[2][4]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row3LEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[3][6]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row4SubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[4][3]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row5PercentPortfolio)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[4][6]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row5SubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $totalportfoliopercent);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (TotalPortfolioPercentage)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[6][3]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row7PercentPortfolio)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $avg_yield);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (AverageYield)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, "");
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (JointBuyerInitialDate)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $participation_percent);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (PercentPortfolioParticipation)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[1][4]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row2LEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $subscription_amount);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (SubscriptionAmount)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $avg_LEplus2);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (AverageLEplus24)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[5][3]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row6PercentPortfolio)\r\n");
fwrite($fdffile1, ">> \r\n");
fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/V (");
fwrite($fdffile1, $rows[6][6]);
fwrite($fdffile1, ")\r\n");
fwrite($fdffile1, "/T (Row7SubscriberMaturityDistribution)\r\n");
fwrite($fdffile1, ">>]\r\n");
fwrite($fdffile1, ">>\r\n");
fwrite($fdffile1, ">>\r\n");
fwrite($fdffile1, "endobj \r\n");
fwrite($fdffile1, "trailer\r\n");

fwrite($fdffile1, "<<\r\n");
fwrite($fdffile1, "/Root 1 0 R\r\n");
fwrite($fdffile1, ">>\r\n");
fwrite($fdffile1, "%%EOF\r\n");
}
fclose($fdffile1);
//}
?>
